DELETE FROM aic_knowledge_article;
DELETE FROM aic_support_ticket;

INSERT INTO aic_knowledge_article (
	ArticleTitle, ArticleCode, OfficeCode, CategoryCode, ArticleType, ContentSummary, SourceLink,
	SafeForSelfService, EscalationBoundary, LastVerified, Active
) VALUES
('Campus Wi-Fi Basic Troubleshooting', 'KA_WIFI_BASIC', 'IT', 'IT_WIFI', 'Troubleshooting', 'Steps for reconnecting to campus Wi-Fi, checking credentials, forgetting network, and reporting unresolved issues.', 'https://example.university.edu/it/wifi-help', 'Yes', 'Escalate if authentication fails after basic troubleshooting or student has urgent assessment deadline.', '2026-06-01', 'Yes'),
('Account Lockout Guidance', 'KA_LOCKOUT', 'IT', 'IT_LOCKOUT', 'Procedure', 'Basic guidance for account lockout, password reset, and when IT verification is needed.', 'https://example.university.edu/it/account-help', 'Yes', 'Escalate if access remains blocked, MFA fails, or student has urgent deadline.', '2026-06-01', 'Yes'),
('Registration Hold FAQ', 'KA_REG_HOLD', 'REG', 'REG_HOLD', 'FAQ', 'Explains common reasons registration holds may appear and what information Registrar needs for review.', 'https://example.university.edu/registrar/holds', 'Yes', 'Escalate when hold requires official record review or manual removal.', '2026-06-01', 'Yes'),
('Medical Certificate Request Guide', 'KA_MED_CERT', 'MED', 'MED_CERT', 'Procedure', 'Provides general guidance on requesting medical certificates and required documentation.', 'https://example.university.edu/health/medical-certificates', 'Yes', 'Escalate for staff review, medical judgment, or official issuance.', '2026-06-01', 'Yes'),
('Student ID Access Troubleshooting', 'KA_SS_ID', 'SS', 'SS_ID', 'Troubleshooting', 'Basic checks for student ID access issues and required details for Student Services escalation.', 'https://example.university.edu/student-services/id-access', 'Yes', 'Escalate if ID access remains denied or building permissions must be checked.', '2026-06-01', 'Yes'),
('Facility Issue Intake', 'KA_SS_FACILITY', 'SS', 'SS_FACILITY', 'Procedure', 'Collects location, issue description, safety urgency, and optional photo evidence for facilities or student services review.', 'https://example.university.edu/student-services/facilities', 'Yes', 'Escalate when the issue affects safety, accessibility, operations, or needs staff action.', '2026-06-01', 'Yes');

INSERT INTO aic_support_ticket (
	TicketNumber, TicketTitle, StudentID, StudentEmail, ResponsibleOfficeCode, CategoryCode, Status,
	Priority, UrgencyReason, IssueSummary, CollectedInformation, MissingInformation, AttemptedGuidance,
	EscalationReason, SuggestedStaffAction, ConversationSummary, Channel, AIConfidence, ResolvedByAgent, CreatedByAgent
) VALUES
('AIC-000001', 'Unable to connect to campus Wi-Fi before online quiz', '2026-00123', 'alex.rivera@student.university.edu', 'IT', 'IT_WIFI', 'Escalated', 'High', 'Student has an online quiz in 20 minutes and cannot access campus Wi-Fi.', 'Student cannot connect laptop to campus Wi-Fi from the library before a quiz.', 'Device: laptop; Location: Library; Network: Campus-Student; Error: cannot authenticate.', 'Exact device operating system version.', 'Forgot network; reconnected with student email; toggled Wi-Fi; restarted browser.', 'Troubleshooting did not resolve issue and student has urgent assessment deadline.', 'Check account authentication status and nearby access point availability.', 'Meera guided the student through basic Wi-Fi troubleshooting. Issue remained unresolved.', 'Chat', 0.91, 'No', 'Yes'),
('AIC-000003', 'Registration hold blocking enrollment', '2025-00890', 'luis.delacruz@student.university.edu', 'REG', 'REG_HOLD', 'Awaiting Student Info', 'High', 'Enrollment deadline is approaching and hold blocks registration.', 'Student sees a registration hold but is unsure why it appears.', 'Term: First Semester 2026; Program/year: BS Psychology, 4th Year.', 'Exact hold message or screenshot.', 'Asked student to provide the hold message shown in the portal.', 'Registrar must review official records to determine the hold reason.', 'Review student record and identify hold source once screenshot/message is provided.', 'Meera classified the concern as Registrar and requested missing hold details.', 'Chat', 0.86, 'No', 'Yes'),
('AIC-000004', 'Medical certificate guidance for absence', '2026-00291', 'bea.tan@student.university.edu', 'MED', 'MED_CERT', 'Resolved', 'Normal', 'Student needs administrative guidance, not urgent medical help.', 'Student asked how to request a medical certificate for an absence.', 'Absence date: 2026-06-05; document requested: medical certificate.', 'None for general guidance.', 'Provided general process and clarified that staff review may be required for issuance.', 'Not escalated; guidance was sufficient.', 'None.', 'Meera provided documentation guidance and student confirmed understanding.', 'Chat', 0.93, 'Yes', 'Yes'),
('AIC-000005', 'Student ID not working at building entrance', '2024-00334', 'noah.garcia@student.university.edu', 'SS', 'SS_ID', 'Escalated', 'Normal', 'Student cannot access a campus building but no immediate exam or deadline was reported.', 'Student ID failed at the entrance gate of a campus building.', 'Location: Science Building; Time: 8:15 AM; Error: access denied.', 'Whether ID works in other buildings.', 'Asked student to test ID at another reader if safe and available.', 'Student Services must check access permissions or ID encoding.', 'Verify ID access status and building permission rules.', 'Meera collected building and time details, then escalated to Student Services.', 'Screen Share', 0.84, 'No', 'Yes');
